aliases: []
creation_timestamp: 1753894190432
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1753894190432
metrics: null
model_id: m-720fb71fa6d94673a63fa61ce124ae40
name: xgboost
params: null
run_id: 36b7efdc6cc749518c9550ed927c07b4
run_link: null
source: models:/m-720fb71fa6d94673a63fa61ce124ae40
status: READY
status_message: null
storage_location: file:///Users/smarthbakshi/projects/football_stream_processor/mlflow/mlruns/729195049582631758/models/m-720fb71fa6d94673a63fa61ce124ae40/artifacts
user_id: null
version: 2
